#
# Common configuration for all devices.
#

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}


# WiFi configuration
wifi:
  # domain: !secret wifi_domain
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".local"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret ota_password

captive_portal:


# Enable logger
logger:


# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key


# Enable OTA updates
ota:
  platform: esphome
  password: !secret ota_password

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time


# Enable web server
web_server:
  port: 80
  version: 3

# ESPHome version sensor
text_sensor:
  - platform: version
    name: Version